### ISSUE TITLE
installation error: File has unexpected size (2408 != 2432). Mirror sync in progress?

### ISSUE THREAD

**Issue by yannickschuchmann** [BlokasLabs/modep-debs#6]
Hey guys,
thank you for your effort in this project.

I got a new rpi4 4gb and pisound the other day and installed the newest patchbox os ([2022-05-17](https://community.blokas.io/t/beta-patchbox-os-image-2022-05-17/3774/13)).

I then ran `sudo apt-get update --allow-releaseinfo-change` and tried to install modep from the `patchbox` wizard and it resulted in the following apt error:

```
Get:51 http://apt.blokas.io/ rpi/main armhf modep-lv2-zam-plugins armhf 3.12.0-2 [6,399 kB]
Get:52 http://apt.blokas.io/ rpi/main armhf modep-touchosc2midi armhf 1.0.0-2 [9,360 B]
Fetched 172 MB in 50s (3,422 kB/s) E: Failed to fetch http://apt.blokas.io/pool/main/m/modep-ctl-scripts/modep-ctl-scripts_1.8.0.deb File has unexpected size (2408 != 2432). Mirror sync in progress? [IP: 79.98.29.34 80]
Hashes of expected file:
- SHA512:a02c18f8637356c4153f231ca15d980cf04d4fb6fbd72e77e07703af7ac5238a4bcbdd7766b5b7f01df0ba5588eab1153fc959731b9acec868d73ee69f1f10fd
- SHA256:f8e91f6684c6849f8a2a352632972a2781d9ab558527a54fa892051ce87f78af
- SHA1:3f43ca0d6c854ac4a119a93a1dad104a3f908890 [weak]
- MD5Sum:924c89707d841556aecb545c5b4d2ac8 [weak]
- Filesize:2432 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Traceback (most recent call last):
File “/usr/lib/python3/dist-packages/patchbox/module.py”, line 621, in _install_module
raise ModuleError(
patchbox.module.ModuleError: Failed to install modep.module via /usr/local/patchbox-modules/modep/install.sh script
```

Seems like a mismatch of versions on the blokas package repo or the repo got compromised.

### Steps to reproduce:
- Fresh install of [2022-05-17](https://community.blokas.io/t/beta-patchbox-os-image-2022-05-17/3774/13)
- SSH into pi, connect with WIFI with internet connection
- `sudo apt-get update --allow-releaseinfo-change --fix-missing` (optional)
- `patchbox update` (optional)
- `sudo apt upgrade` (optional)
- Install modep: `patchbox module activate modep` or through `patchbox` wizard

I tested the optional steps in all combinations. Same outcome.

Any idea?

Cheers :)

**Comment by gtrainavicius** [comment]
Fixed in our server, run `sudo apt update` and try installing again. :)
