### ISSUE TITLE
submodule ref of modep-lv2-fil4 does not exist

### ISSUE THREAD

**Issue by yannickschuchmann** [BlokasLabs/modep-debs#7]
I'm trying to build and install the modep packages locally. I'd also write some documentation how to do, so that it's easier for contributors to get started. I got the idea because of the currently not working standard installation method via apt.

While installing submodules of this repo via 
```
git submodule update --init --recursive
```

I get the following error:
```
fatal: remote error: upload-pack: not our ref 05f84c3ea9ecc48892f0ef70309c8375a1fbb01a
Fetched in submodule path 'modep-lv2-fil4/src', but it did not contain 05f84c3ea9ecc48892f0ef70309c8375a1fbb01a. Direct fetching of that commit failed.
```

So I checked the referenced submodule path of modep-lv2-fil4 and it leads to a 404:
https://github.com/BlokasLabs/fil4.lv2/tree/05f84c3ea9ecc48892f0ef70309c8375a1fbb01a

@gtrainavicius, since it works locally for you guys, is it possible that some commits are not pushed yet to the github remote repo?

Thanks for help :) Enjoy your weekends 🌞

**Comment by gtrainavicius** [comment]
Yes, forgot to push this commit, it's available now. :)
